### ISSUE TITLE
Problem building nerves_interim_wifi with cache for 0.6.1

### ISSUE THREAD

**Issue by paulanthonywilson** [nerves-project/nerves_system_rpi#5] opened 2016-09-27 17:16 UTC
tldr; pinning to `nerves_toolchain` version 0.6.3 is a workaround.

Issue. Building `nerves_interim_wifi`, and probably other libraries that need to be compiled to the target, fails something like below

```
Updating base firmware image with Erlang release...
scrub-otp-release.sh: ERROR: Unexpected executable format for '/Users/paul/dev/elixir/nerves/code/scratch/_nerves-tmp/rootfs-additions/srv/erlang/lib/nerves_interim_wifi-0.1.0/priv/udhcpc_wrapper'

Got:
 ELF 32-bit LSB executable, ARM, version 1, dynamically linked (uses shared libs), for GNU/Linux 3.12.55

If binary, expecting:
 ELF 32-bit LSB executable, ARM, version 1, dynamically linked (uses shared libs), for GNU/Linux 3.4.110

or, for static binaries:
 ELF 32-bit LSB executable, ARM, version 1, statically linked, for GNU/Linux 3.4.110

If shared library, expecting:
 ELF 32-bit LSB shared object, ARM, version 1

 This file may have been compiled for the host or a different target.
 Make sure that nerves-env.sh has been sourced and rebuild to fix this.
```

Right now you can reproduce by cloning and building the firmware for this  https://github.com/paulanthonywilson/nerves_interim_wifi_woes

This is fixed by pinning the `nerves_toolchain` to 0.6.3. See https://github.com/paulanthonywilson/nerves_interim_wifi_woes/pull/1/files

**Comment by fhunleth** [comment] 2016-09-28 00:21
@mobileoverlord Have you looked into this?

I'm on Linux and I'm getting the correct formats.

However, it's trying to run the port binaries on my system:
```
fhunleth@halfmarathon:~/nerves/nerves_interim_wifi_woes (master)$ mix

=INFO REPORT==== 27-Sep-2016::20:14:55 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application nerves_network_interface: Nerves.NetworkInterface.start(:normal, []) returned an error: shutdown: failed to start child: Nerves.NetworkInterface.Worker
    ** (EXIT) an exception was raised:
        ** (ErlangError) erlang error: :enoent
            :erlang.open_port({:spawn_executable, '/home/fhunleth/nerves/nerves_interim_wifi_woes/_build/rpi/dev/lib/nerves_network_interface/priv/netif'}, [{:packet, 2}, :use_stdio, :binary])
            (nerves_network_interface) lib/network_interface/worker.ex:67: Nerves.NetworkInterface.Worker.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by mobileoverlord** [comment] 2016-09-28 00:23
I am mobile right now, I'll be able to get to this tonight / tomorrow morning.

**Comment by paulanthonywilson** [comment] 2016-09-28 13:23
I should have mentioned that I'm running on OS X.

**Comment by mobileoverlord** [comment] 2016-09-28 13:33
I started looking into this and then realized I didn't have any coffee. So that's the first problem 🤓

**Comment by mobileoverlord** [comment] 2016-09-28 15:07
The issue is that the toolchain for armv6 / darwin was not updated to build for kernel 3.12
Fixed in:
nerves-project/toolchains@bb7bcdc724286b8577eeb20c4dca943c08a038dd

Once I am done building it I'll push it to hex

**Comment by paulanthonywilson** [comment] 2016-09-28 15:19
👍 Thanks for looking into this, and hope you got enough coffee.

**Comment by jeffutter** [comment] 2016-10-04 17:27
Any update on this being pushed to hex?

**Comment by fhunleth** [comment] 2016-10-06 04:24
@jeffutter: Justin hasn't had internet for several days. I'm not sure what happened with pushing the updated version. I'll see if I can reach Justin and get a new version posted soon.

**Comment by mobileoverlord** [comment] 2016-10-07 20:14
Hi everyone. I finally have internet again and was able to get the update out and pushed to hex. Please update your dependency for the toolchain, this should fix the issue.

`mix deps.update nerves_toolchain_armv6_rpi_linux_gnueabi`

Sorry for the delay, moving stinks!

**Closed** 2016-10-07 20:15 UTC
